# Generated by Django 3.2.1 on 2023-08-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lunarlink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='这个项目所属的分组', to='auth.Group', verbose_name='分组'),
        ),
    ]
