# Generated by Django 3.2.1 on 2023-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunarlink', '0002_project_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPurposeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'general_purpose',
                'permissions': [('custom_permission', 'Can perform a custom action')],
            },
        ),
    ]
