# Generated by Django 3.2.1 on 2023-11-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunarlink', '0003_generalpurposemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalpurposemodel',
            options={'permissions': [('custom_permission', 'Can perform a custom action')], 'verbose_name': '自定义权限'},
        ),
    ]
