# Generated by Django 3.2.1 on 2023-11-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunarlink', '0004_alter_generalpurposemodel_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralPurposeModel',
        ),
    ]
