# Generated by Django 3.2.1 on 2024-01-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunarlink', '0006_auto_20240111_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='case',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='casestep',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='config',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='debugtalk',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='hostip',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='report',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='creator',
        ),
    ]
