# Generated by Django 3.2.1 on 2024-01-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunarlink', '0007_auto_20240111_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='create_by',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='create_by',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='casestep',
            old_name='create_by',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='create_by',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='debugtalk',
            old_name='create_by',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='hostip',
            old_name='create_by',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='create_by',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='create_by',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='variables',
            old_name='create_by',
            new_name='creator',
        ),
    ]
