# Generated by Django 3.2.1 on 2024-01-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunarlink', '0008_auto_20240111_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='modifier',
            field=models.IntegerField(help_text='修改人', null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='case',
            name='modifier',
            field=models.IntegerField(help_text='修改人', null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='casestep',
            name='modifier',
            field=models.IntegerField(help_text='修改人', null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='config',
            name='modifier',
            field=models.IntegerField(help_text='修改人', null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='debugtalk',
            name='modifier',
            field=models.IntegerField(help_text='修改人', null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='hostip',
            name='modifier',
            field=models.IntegerField(help_text='修改人', null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='project',
            name='modifier',
            field=models.IntegerField(help_text='修改人', null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='report',
            name='modifier',
            field=models.IntegerField(help_text='修改人', null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='variables',
            name='modifier',
            field=models.IntegerField(help_text='修改人', null=True, verbose_name='修改人'),
        ),
    ]
