# Generated by Django 3.2.1 on 2024-01-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunarlink', '0009_auto_20240112_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='case',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='casestep',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='config',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='debugtalk',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='hostip',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updater',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='updater',
        ),
    ]
