# Generated by Django 3.2.1 on 2024-01-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunarlink', '0012_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='name',
            field=models.CharField(blank=True, help_text='登录用户姓名', max_length=20, null=True, verbose_name='登录用户姓名'),
        ),
    ]
