# Generated by Django 3.2.1 on 2024-04-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunarlink', '0013_loginlog_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostIP',
        ),
    ]
