# Generated by Django 3.2.1 on 2023-11-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunaruser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(blank=True, help_text='姓名', max_length=40, null=True, verbose_name='姓名'),
        ),
    ]
